config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "landing#show"
  get "/vehicles/search" => redirect("/vehicles")

  if Rails.env.development?
    require "sidekiq/web"
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :vehicles, only: [:index] do
    collection do
      post :search
    end
  end

  resources :user_vehicles, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_vehicles
  has_many :vehicles, through: :user_vehicles
end

app/models/user_vehicle.rb
class UserVehicle < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  before_save :set_default_color

  def set_default_color
    self.color ||= "unknown"
  end

  def self.build_from_fleetio_vehicle(fleetio_vehicle)
    new(fleetio_vehicle.slice("make", "model", "color", "vin", "year")).tap do |vehicle|
      vehicle.fleetio_id = fleetio_vehicle["id"]
    end
  end

  def name
    "#{year} #{make} #{model}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def show
  end
end

app/controllers/user_vehicles_controller.rb
class UserVehiclesController < ApplicationController
  def create
    @user_vehicle = current_user.user_vehicles.new(user_vehicle_params)

    if @user_vehicle.save
      flash[:success] = "Your vehicle was successfully saved"
      redirect_to vehicles_path
    else
      # TODO: do something on failure
      # render errors
    end
  end

  private

  def user_vehicle_params
    params.require(:user_vehicle).permit(:vehicle_id)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  helper_method :allow_save?

  def index
    setup_view_context
  end

  def search
    session[:vin] = params[:vin]
    setup_view_context
    render :index
  end

  private

  def allow_save?
    @allow_save ||= @vehicle.present? && current_user.present? && !current_user.vehicles.where(id: @vehicle.id).exists?
  end

  def setup_view_context
    @vin = session[:vin]
    @remote_vehicle = nil
    @vehicle = @vin.present? ? ProvideVehicle.execute(@vin) : nil
    @saved_vehicles = current_user.present? ? current_user.vehicles : []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/landing/show.html.erb
<div class="flex lg:flex-col">
  <div class="flex align-middle items-center w-full justify-center h-screen" style="min-height: 34em;">
    <div class="flex landing-search-wrapper bg-white p-6 rounded-lg shadow-lg">
      <div class="landing-search-help w-1/3 border-r mr-5 py-4">
        <h2 class="text-4xl mb-6 font-extrabold uppercase text-gray-800">Find Your Whip</h2>
        <p class="text-gray-600 w-10/12">
          Thousands of vehicles are just a few key strokes away. Get started by typing your vehicle's vin number.
        </p>
      </div>
      <div class="landing-search-form w-2/3 py-8">
        <%= form_tag(search_vehicles_path, method: :post) do %>
          <div>
            <%= text_field_tag :vin, nil, class: "bg-white focus:outline-none focus:shadow-outline border border-gray-300 rounded-lg mt-6 py-2 px-4 block w-full appearance-none leading-normal", placeholder: "enter the VIN number..." %>
          </div>
          <input type="submit" class="bg-blue-500 hover:bg-blue-800 cursor-pointer text-white font-normal py-2 px-4 rounded focus:outline-none focus:shadow-outline float-right mt-2" value="Search" id="search_submit" />
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_top_nav.html.erb
<nav class="flex items-center justify-between flex-wrap p-6 shadow-md" style="background: #212B4B">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <svg class="fill-current h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
    <span class="font-semibold text-xl tracking-tight">Vehicle Finder</span>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow"></div>
    <% if current_user.nil? %>
      <div>
        <%= link_to "Log in", new_user_session_path, class: "inline-block text-xs px-4 py-2 leading-none text-white hover:text-blue-500 mt-4 lg:mt-0 uppercase font-semibold" %>
      </div>
      <div>
        <%= link_to "Sign Up", new_user_registration_path, class: "inline-block text-xs px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue-500 hover:bg-white mt-4 lg:mt-0 uppercase font-semibold" %>
      </div>
    <% else %>
      <span class="text-white inline-block border-r border-white pr-4 mr-4">Welcome, <%= current_user.name %></span>
      <%= link_to "Log out", destroy_user_session_path, class: "inline-block text-xs px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue-500 hover:bg-white mt-4 lg:mt-0 uppercase font-semibold" %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FleetioInventorySearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="antialiased">
    <%= render '/layouts/top_nav' %>
    <%= yield %>
  </body>
</html>

app/views/user_vehicles/create.html.erb
<h1>UserVehicles#create</h1>
<p>Find me in app/views/user_vehicles/create.html.erb</p>

app/views/vehicles/_card.html.erb
<div class="flex" id="vehicle_card">
  <div class="flex w-3/5 bg-white rounded shadow-2xl p-4">
    <div class="flex w-2/5">
      <div class="block bg-gray-100 border-gray-200 h-64 w-full mr-6"></div>
    </div>
    <div class="w-3/5">
      <div class="w-full">
        <h2 class="font-semibold text-lg">
          Vehicle - <%= vehicle.vin %>
        </h2>
      </div>
      <div class="flex mt-4">
        <div class="w-3/4 text-sm">
          <ul>
            <li class="mb-2"><span class="font-semibold w-16 inline-block">Year:</span> <%= vehicle.year %></li>
            <li class="mb-2"><span class="font-semibold w-16 inline-block">Make:</span> <%= vehicle.make %></li>
            <li class="mb-2"><span class="font-semibold w-16 inline-block">Model:</span> <%= vehicle.model %></li>
          </ul>
        </div>
        <div class="w-1/2 text-sm">
          <ul>
            <li class="mb-2"><span class="font-semibold w-16 inline-block">Color:</span> <%= vehicle.color %></li>
            <li class="mb-2">
              <span class="font-semibold w-16 inline-block">Fuel Eff:</span>
              <% if vehicle.fuel_efficiency.present? %>
                <%= vehicle.fuel_efficiency %>
              <% else %>
                TBD
              <% end %>
            </li>
          </ul>
        </ul>
      </div>
    </div>
    <div class="w-full mt-20">
      <%= form_with model: UserVehicle.new(user: user), remote: false, class: "nifty_form" do |f| %>
        <% if allow_save %>
          <%= f.submit "Save for later", class: "bg-blue-500 hover:bg-blue-800 cursor-pointer text-white font-normal py-3 px-4 rounded focus:outline-none focus:shadow-outline text-sm uppercase w-full text-center" %>
        <% else %>
          <%= f.submit "Save for later", class: "bg-gray-400 cursor-not-allowed text-white font-normal py-3 px-4 rounded focus:outline-none focus:shadow-outline text-sm uppercase w-full text-center", disabled: true %>
        <% end %>
        <%= f.hidden_field :vehicle_id, value: vehicle.id %>
      <% end %>
    </div>
  </div>
</div>

app/views/vehicles/_empty_card.html.erb
<div class="flex">
  <div class="flex w-3/5 bg-white rounded shadow-2xl p-4" style="min-height: 290px;">
    <div class="w-full mt-6 p-6">
      <h2 class="text-gray-800 text-5xl">Nothing to see here</h2>
      <h3 class="text-gray-800 text-3xl">Start by searching above</h3>
    </div>
  </div>
</div>

app/views/vehicles/_error_card.html.erb
<div class="flex">
  <div class="flex w-3/5 bg-white rounded shadow-2xl p-4" style="min-height: 290px;">
    <div class="w-full mt-6 p-6">
      <h2 class="text-gray-800 text-5xl">We're sorry</h2>
      <h3 class="text-gray-800 text-3xl">A vehicle couldn't be found</h3>
    </div>
  </div>
</div>

app/views/vehicles/_saved_vehicles.html.erb
<div class="flex fixed w-4/12 right-0" style="top: 234px; min-height: 290px; right: 1em;" id="saved_vehicles">
  <div class="border-gray-200 w-full shadow-2xl bg-white rounded">
    <h2 class="font-semibold bg-blue-800 text-white p-4">Your Vehicles</h2>

    <% if vehicles.any? %>
      <ul class="px-4 py-2">
        <% vehicles.each do |vehicle|%>
          <li class="px-4 py-2 my-2 border-b border-gray-200">
            <%= link_to vehicle.name, "#", class: "text-blue-500 hover:text-blue-800" %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <div class="flex bg-gray-100 m-2 p-2 border-dashed border-gray-300 border-2 text-gray-700 h-56">
        <% if user.present? %>
          <p class="my-auto text-center w-full text-lg">
            Nothing here yet. <br />
            Start saving some vehicles!
          </p>
        <% else %>
          <p class="my-auto text-center w-full text-lg">
            Log in or create an account <br />
            to start saving vehicles
          </p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/vehicles/index.html.erb
<div class="flex bg-white shadow-lg w-full">
  <div class="w-full py-4 px-6">
    <%= form_tag(search_vehicles_path, method: :post) do %>
      <div class="relative">
        <%= text_field_tag :vin, @vin, class: "bg-white focus:outline-none focus:shadow-outline border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal", placeholder: "enter the VIN number..." %>
        <%= submit_tag "Search", class: "bg-blue-500 hover:bg-blue-800 cursor-pointer text-white font-normal py-3 px-4 rounded focus:outline-none focus:shadow-outline float-right mt-2 absolute", style: "top: -11px; right: -5px;" %>
      </div>
    <% end %>
  </div>
</div>

<div class="flex text-white text-sm font-bold h-12">
  <% if flash[:success].present? %>
    <div class="flex bg-green-500 w-full px-6 py-3" role="alert">
      <p><%= flash[:success] %></p>
    </div>
  <% end %>
</div>


<%= render 'saved_vehicles', vehicles: @saved_vehicles, user: current_user %>

<div id="search_results" class="mt-8 mx-6">
  <%= render 'error_card' if @vehicle.nil? && session[:vin].present? %>
  <%= render 'empty_card' if @vehicle.nil? && session[:vin].blank? %>
  <%= render 'card', vehicle: @vehicle, user: current_user, allow_save: allow_save? if @vehicle %>
</div>

app/views/vehicles/show.html.erb
<h1>Vehicles#show</h1>
<p>Find me in app/views/vehicles/show.html.erb</p>